name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install zlib (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat
        .\vcpkg\vcpkg.exe install zlib:x64-windows-static
        Write-Host "=== installed root ==="
        dir "${{ github.workspace }}\vcpkg\installed\x64-windows-static" -Recurse -Filter "*.lib" | Select-Object FullName
        exit 1
    - name: Set Rust/zlib environment variables
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        echo "ZLIB_LIB_DIR=${{ github.workspace }}\vcpkg\installed\x64-windows-static\lib" >> $env:GITHUB_ENV
        echo "ZLIB_INCLUDE_DIR=${{ github.workspace }}\vcpkg\installed\x64-windows-static\include" >> $env:GITHUB_ENV
        echo "LIBZ_SYS_STATIC=1" >> $env:GITHUB_ENV
    - name: Set Rust/zlib environment variables
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        echo "ZLIB_LIB_DIR=${{ github.workspace }}\vcpkg\installed\x64-windows-static\lib" >> $env:GITHUB_ENV
        echo "ZLIB_INCLUDE_DIR=${{ github.workspace }}\vcpkg\installed\x64-windows-static\include" >> $env:GITHUB_ENV
        echo "LIBZ_SYS_STATIC=1" >> $env:GITHUB_ENV
    - name: Build
      run: cargo build --verbose --all-features
    - name: Test (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $env:ZLIB_LIB_DIR = "${{ github.workspace }}\vcpkg\installed\x64-windows-static\lib"
        $env:ZLIB_INCLUDE_DIR = "${{ github.workspace }}\vcpkg\installed\x64-windows-static\include"
        $env:LIBZ_SYS_STATIC = "1"
        cargo test --verbose --all-features
    - name: Test (Linux)
      if: runner.os == 'Linux'
      run: cargo test --verbose --all-features
    # - name: Run tests
      # run: cargo test --verbose --all-features
      
